config/routes.rb
Rails.application.routes.draw do

  get 'gallery/media'

  devise_for :users
  resources :posts
  resources :contacts, only: [:new, :create]
  
  get 'welcome/index'
  root 'welcome#index'
  
  get 'programs/refugees'
  get 'programs/social_and_cultural'
  get 'programs/women'
  get 'programs/sport_recreational'
  get 'programs/community_language'
  get 'programs/english'

  get 'pages/about'
  
  get 'student_branches/curtin_salsaal'

  get 'gallery/media'



  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,   :validate => true
	attribute :nickname,  :captcha  => true

  	def headers
  	{
	  	:subject => "Salsaal Contact Form",
	  	:to => "president@salsaal.org.au",
	  	:from => %("#{name}" <#{email}>)
	  }
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
	    @contact.request = request
	    if @contact.deliver
	      flash.now[:error] = nil
	    else
	      flash.now[:error] = 'Cannot send message.'
	      render :new
	    end
	end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def media
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
		
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Updated, Mortaza"
		else
			render 'new', notice: "Oh no, failed to post update"
		end

	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Successfully Updated Post"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def refugees
  end

  def social_and_cultural
  end

  def women
  end

  def sport_recreational
  end

  def community_language
  end

  def english
  end
end

app/controllers/student_branches_controller.rb
class StudentBranchesController < ApplicationController
  def curtin_salsaal
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(2).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
	        no_intra_emphasis: true,
	        disable_indented_code_blocks: true,
	        fenced_code_blocks: true,
	        lax_html_blocks: true,
	        strikethrough: true,
	        superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe

	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/student_branches_helper.rb
module StudentBranchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Contact us</h1>
<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for contacting Us</h1>
	<p>We will get back to you as soon as possible</p>
</div>

app/views/contacts/new.html.erb
<div class="contact_header">
	<h1>Contact Us</h1>
	<br>
	<i class="fa fa-mobile" id="mobile"> +61 449 894 366</i><br>
	<i class="fa fa-envelope"> admin@salsaal.org.au | president@salsaal.org.au</i>
</div>
<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %> <br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %> <br>
		<%= f.text_field :email, required: true %>
		<br>


		<%= f.label :message %> <br>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %> <br>
			<%= f.text_area :nickname, hint: 'used to detect spam' %>
		</div>
		<br>
		<br>
		<%= f.submit 'Send Message', class: "btn btn-primary"%>
	<% end %>

</div>

app/views/gallery/media.html.erb
<h1 id="page_title">Gallery</h1>
<div class="container">
	<div class="salsaal_images">
	    <%= image_tag("protest.JPG", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
	    <%= image_tag("national_communication_conference.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
	    <%= image_tag("refugee_info_session.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
		<%= image_tag("english_level1.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
		<%= image_tag("english_level2.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
		<%= image_tag("dari_level1.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>
		<%= image_tag("dari_level2.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "1200x900")%>
	    <br>



    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<%= favicon_link_tag 'favicon.png' %>
		
	<!-- font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

	<title>Salsaal Integeration Association Inc.</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar_id"> <!-- START OF NAVIGATION BAR -->
		<div class="container"><!-- START OF CONTAINER -->
			<div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <%= link_to image_tag("logo.png", class: "img-responsive"), root_path, class:"name" %>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav" id="navbar_menus">
				  <li><%= link_to "Home", root_path%></li>
				  <li><%= link_to "About Us", pages_about_path%></li>
				  <li><%= link_to "Latest News", posts_path %></li>

				  <li class="dropdown">
				    <a href="" class="visible-xs dropdown-toggle" data-toggle="dropdown">Activities<b class="caret"></b></a>
					<a href="" class="hidden-xs">Activities<b class="caret"></b></a>
				    <ul class="dropdown-menu">
				      <li><%= link_to "Cultural Program", programs_social_and_cultural_path%></li>
				      <li><%= link_to "Women and Youth Program", programs_women_path%></li>
				      <li><%= link_to "Sport and Recreational Program", programs_sport_recreational_path%></li>
				      <li><%= link_to "Community Language School (Dari/Farsi)", programs_community_language_path%></li>
				      <li><%= link_to "English Program", programs_english_path%></li>
				      <li><%= link_to "Refugees and Asylum Seekers", programs_refugees_path%></li>
				      
				    </ul>
				  </li>
				  <li class="dropdown">
				    <a href="" class="visible-xs dropdown-toggle" data-toggle="dropdown">Student Branches<b class="caret"></b></a>
					<a href="" class="hidden-xs">Student Branches<b class="caret"></b></a>				    <ul class="dropdown-menu">
				      <li><%= link_to "Curtin Salsaal Students Association", student_branches_curtin_salsaal_path%></li>
				    </ul>
				  </li>
				  
				  <li><%= link_to "Contact Us", new_contact_path %></li>

				  <% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				  <% end %>
				</ul>
			</div>
		</div><!-- END OF CONTAINER -->
	</nav><!-- END OF NAVIGATION BAR -->

	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert%>
       <p class="alert"><%= alert %></p>
    <% end %>


	<%= yield %>

	<footer id="main_footer">
		<p class="copyright">&copy; 2015 Salsaal Integration Association Inc.</p>
		<nav class = "footer_share">
			<a href="https://www.facebook.com/Salsaal-Integration-Association-Inc-Perth-WA-1508366149425822" target="_blank"><i class="fa fa-facebook fa-lg" id="icons"></i></a>
			<a href="https://www.twitter.com" target="_blank"><i class="fa fa-twitter fa-lg" id="icons"></i></a>
		</nav>

		<p id="footer_signature">Developed by Mortaza Rezae</p>

	</footer>

</body>
</html>

app/views/pages/about.html.erb
<h1 id="page_title">About Us</h1>
<div class="container">
	<br>
	<p>Salsaal Integration Association was founded in August 2014 by a group of like-minded and committed Afghans in Western Australia. SIA is a non-for-profit organisation aims to provide extensive ranges of cultural, educational and recreational programs and promote awareness between people of diverse communities in Western Australia. SIA empowers the learning opportunities of the Perth Culturally and Linguistically Diverse (CaLD) residents, especially the Afghans, by organising cultural events such as New Year (Nowrooz) eve and Eid; educational programs such as offering free Dari, Hazaragi and English programs for new arrivals refugees and children;  women empowerment programs such as celebrating International Women Day; empowering students and youth in the community such as establishing Curtin Salsaal Student Association and organising football and other sport tournaments; and organising other civic and recreational programs to promote awareness and respect between people of different communities in Perth, Western Australia.</p>
	<p>Mr. Shoukat Lali became the first elected interim President of SIA with responsibilities to register the organisation with the Department of Commerce and initiate necessary arrangement for the next stage to elect a new President with full capacity. After being registered with the Department of Commerce, under Associations Incorporation Act 1987 in November 2014, SIA formally began promoting its activities in Perth, Western Australia.</p>
	<p>In February 2015, Deedar Khudaidad was elected as President to carry on the activities of SIA with full capacity. After celebrating the International Women’s Day in March 2015 and organising other cultural events, SIA quickly became popular for its extensive ranges of cultural, educational and recreational programs implemented at the North and Southern suburbs of Perth. Since then, SIA’s dedicated members are tirelessly working to bring new initiatives in the community, expanding SIA’s activities around Perth and state-wide, and making sure our people in the community receive necessary services.</p>

	<p>Our objectives are as follows:</p>
	<ul>
		<li type="a">Promoting an environment of growth, culture exchange and friendship among the people of Australia with diverse backgrounds;</li>
		<li type="a">Fostering an environment to help maintaining culture, traditions and moral values of the Afghan people as well as to adapt to applicable values of the local Australian community in harmonious way;</li>
		<li type="a">Presenting Afghan cultures to the Australian society by holding cultural events such as Eid, Nowrooz and other ceremonies/events by inviting people for CaLD communities;</li>
		<li type="a">Sponsoring Afghan artists, singers and musicians and academics for delivering our voices through their arts, presentations, expertise and professions;</li>
		<li type="a">Providing a forum of friendly environment where Afghan women discusses their issues that are important to their life;</li>
		<li type="a">Creating attractive recreational and educational activities for Afghan women and children who are isolated in the community;</li>
		<li type="a">Creating a forum where Salsaal members and community at large can discuss and explore issues and ideas relevant to their day-to-day life;</li>
		<li type="a">Creating an interactive network of students and promoting culture of understanding among Afghan students to pursue their higher education;</li>
		<li type="a">Promoting awareness among people to respect each other's believes and faith;</li>
		<li type="a">Raising funds and donations for the organisation to run its activities independently</li>
		<li type="a">And promoting the ideas and philosophy of working as a team</li>

	</ul>
	<br>
	<div class="salsaal_images">
	    <%= image_tag("organisational_chart.jpg", class: "img-responsive salsaal_images", :align=> "middle")%>
	    <br>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%=pluralize(post.errors.count, "error") %> prevented this update from saving: </h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, "Write your update here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>

	<%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Latest News</h1>
		

<div id="events_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
	<div class="event">
		<p class="date">Posted On: <%= post.created_at.strftime("%A, %b %d %Y") %></p>
		<h2><a href="#"><%= link_to post.title, post, {:style=>'color:#1374a5;'}%></a></h2>
		<p class="truncated_p"><%=markdown truncate post.content, length: 350%></p>
		<p class="read_more"><%= link_to "read more ..", post,  {:style=>'color:#1374a5;'}%></a>
		<hr>
	</div>
	<% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime("%A, %b %d %Y") %></p>
		<h1><%=@post.title %></h1>
		<hr>
	</header>
	
	<div id="content">
		<%= markdown @post.content %>
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "Edit Post", edit_post_path(@post) %>
			<%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure>"} %>
		</div>
	<% end %>

	<hr>
	<div id="share_box">
		<p>Share This Update</p>
		<!-- Twitter -->
    	<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    	<!-- Facebook -->
    	<a onclick="javascript:window.open('https://www.facebook.com/sharer/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
	</div>
	<hr>
</div>


<br/>
<br/>

app/views/programs/community_language.html.erb
<h1 id="page_title">Community Language School (Dari/Farsi)</h1>
<div class="container">
	<br>
	<p>In the last one year, we have been extensively engaged with community elders, families, parents and people of all age groups to discuss and find our community needs. Among many wants and needs, we found that establishing a community language school to teach the Afghan children their mother tongue, Dari/Farsi language, is one of the community’s top priority needs in Western Australia. Most of the Afghan children, especially those who were born and raised in Australia, are fluent in English but cannot speak their mother tongue, Dari/Farsi. On the other hand, their parents are fluent in Dari/Farsi but cannot speak English. As result, most of Afghan parents fails to maintain effective communication with their children.</p>
	<p>Additionally, Afghan Australians are very keen to maintain their heritage and culture. Therefore, they keep communicating with each other’s and their family members in their own language, Dari Farsi.</p>
	<p>Therefore, Salsaal Dari School was established in June 2015 to overcome the issue of intern-generational problems, strengthening community language, culture and heritage, and teaching Dari/Farsi language for Afghan children who are born or raised in Australia and have had difficulties in reading, writing, listening and speaking.</p>
	<p>Since its establishment, The City of Gosnells has been providing us venue at the Knowledge Centre to continue our classes, and the Office of Multicultural Interests together with the Australian Federation of Ethnic Schools Associations Inc. are providing professional trainings for our teachers and volunteers.</p>
	<p>SIA planned to start its Dari School on February 2016 and finishes concurrently with school period in December of the same year. At the moment, Salsaal’s Dari School is operating at the Knowledge Centre, City of Gosnells, covering south of the river only. From 2016 onwards, SIA planned to open another branch at the City of Stirling, covering north of the river as well.</p>
	<br>
	<div class="salsaal_images">
	    <%= image_tag("dari.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "800x600")%>
	    <br>
	    <%= image_tag("dari_level1.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "800x600")%>
	    <br>
	    <%= image_tag("dari_level2.jpg", class: "img-responsive salsaal_images", :align=> "middle", :size => "800x600")%>
	    <br>
    </div>

</div>

app/views/programs/english.html.erb
<h1 id="page_title">English Program</h1>
<div class="container">
	<h3>Events</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>

</div>

app/views/programs/refugees.html.erb
<h1 id="page_title">Refugees and Asylum Seekers</h1>
<div class="container">
	<h3>Events</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>

</div>

app/views/programs/social-and-cultural.html.erb
<h1 id="page_title">Programs</h1>
<div class="container">
	<h3>Social And Cultural</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>
</div>

app/views/programs/social_and_cultural.html.erb
<h1 id="page_title">Cultural Program</h1>
<div class="container">
	<h3>Events</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>
</div>

app/views/programs/sport_recreational.html.erb
<h1 id="page_title">Sport and Recreational Program</h1>
<div class="container">
	<h3>Events</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>

</div>

app/views/programs/women.html.erb
<h1 id="page_title">Women</h1>
<div class="container">
	<h3>Events</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>
</div>

app/views/student_branches/curtin_salsaal.html.erb
<h1 id="page_title">Curtin Salsaal Students Association</h1>
<div class="container">
	<h3>Description</h3>
	<p>Content coming soon...</p>
	<p>Stay tuned!</p>
</div>

app/views/welcome/index.html.erb
<div class="container"> <!-- START OF CONTAINER -->
	<!-- Carousel
	================================================== -->
	<div id="myCarousel" class="carousel slide">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	  </ol>
	  <div class="carousel-inner">
	    <div class="item active">
		  <%=image_tag("refugee_info_session.jpg", class: "img-responsive", :size => "1500x400")%>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>Refugee Information Session</h1>
	          <p><%= button_to('Learn More', gallery_media_path, :class => 'btn btn-primary', :method => "get")%></p>
	        </div>
	      </div>
	    </div>
	    <div class="item">
		  <%=image_tag("dari_level1_cropped.jpg", class: "img-responsive", :size => "1500x400")%>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>Kids' Dari Program</h1>
	          <p><%= button_to('Learn More', gallery_media_path, :class => 'btn btn-primary', :method => "get")%></p>
	        </div>
	      </div>
	    </div>
	    <div class="item">
		  <%=image_tag("adult_english.jpg", class: "img-responsive", :size => "1500x400")%>
	      <div class="container">
	        <div class="carousel-caption">
	          <h1>Adult English Program</h1>
	          <p><%= button_to('Learn More', gallery_media_path, :class => 'btn btn-primary', :method => "get")%></p>
	        </div>
	      </div>
	    </div>
	  </div>
	  <!-- Controls -->
	  <a class="left carousel-control" href="#myCarousel" data-slide="prev" id="left_carousel">
	    <span class="icon-prev"></span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" data-slide="next">
	    <span class="icon-next"></span>
	  </a>  
	</div>
	<!-- /.carousel -->

	<div class="wrapper wrapper_padding clearfix">
		<div class="col-1 homepage_content">
			<h2>Latest News</h2>
			<hr>


			<% @posts.each do |post| %>
				<h3><a href="#"><%= link_to post.title, post, {:style=>'color:#1374a5;'}%></a></h3>
				<p class="truncated_p"><%=markdown truncate post.content, length: 150%></p>
				<p class="read_more"><%= link_to "read more ..", post,  {:style=>'color:#1374a5;'}%></a>
				<p class="date">Posted On: <%= post.created_at.strftime("%A, %b %d %Y") %></p>
			<% end %>

		</div>
		<div class="col-2 homepage_content">
			<h2>Dari Classes</h2>
			<hr>
			<h3>Every Saturday at 10 am</h3>
			<p>Brooklyn forage 3 wolf moon typewriter, kinfolk portland wayfarers taxidermy letterpress. Master cleanse street art pork belly try-hard, wolf skateboard viral irony tofu.</p>
			<p>Brooklyn forage 3 wolf moon typewriter, kinfolk portland wayfarers taxidermy letterpress. Master cleanse street art pork belly try-hard, wolf skateboard viral irony tofu.</p>


		</div>
		<div class="col-3 homepage_content">
			<h2>English Classes</h2>
			<hr>
			<h3>Every Sunday at 5pm</h3>
			<p>Brooklyn forage 3 wolf moon typewriter, kinfolk portland wayfarers taxidermy letterpress. Master cleanse street art pork belly try-hard, wolf skateboard viral irony tofu.</p>
		</div>
	</div>
</div> <!-- END OF CONTAINER -->